print("😎👍")
a=True
b=False
c=True
print(a and a)
print(b and b ) 
print(not c )
print(not b)
print(not a)
print(a and b)
print(b and c )
print(a or c)
print(b or c)
print(c or a )
print(c or b )
print(c or c)
nome= 'geovanna\npaula'
print(nome[0])
print(nome[2:4])
print(nome[-3:-1])
print(nome[-3:])
print(nome[4:5])
print(nome[-19:])
print(nome.startswith("smart"))
print(len(nome))
print(nome)
print(nome.strip())
print(nome.lower())
print(nome.upper())